=== catamaran2/catamaran2-B0WCKKxmlGyak/B0WCKK_1027/szemelyek.dtd
<!ELEMENT szemelyek (#PCDATA | szemely)*>
<!ELEMENT szemely (#PCDATA | nev | kor | város)*>
<!ELEMENT város (#PCDATA)>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT kor (#PCDATA)>

=== catamaran2/catamaran2-B0WCKKxmlGyak/B0WCKK_1027/szemelyek.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE szemelyek SYSTEM "file:/G:/Oxygen%20XML%20Editor%2023/projects/szemelyek.dtd">

<szemelyek>
    <szemely>
        <nev>Dóra</nev>
        <kor>25</kor>
        <város>Budapest</város>
    </szemely>
    <szemely>
        <nev>Jani</nev>
        <kor>25</kor>
        <város>Budapest</város>
    </szemely>
    <szemely>
        <nev>Timi</nev>
        <kor>25</kor>
        <város>Budapest</város>
    </szemely>
    
    
</szemelyek>
