=== catamaran2/catamaran2-B0WCKKxmlGyak/B0WCKK_1103/szemelyek.dtd
<!ELEMENT szemelyek (szemely+)>
<!ELEMENT szemely (nev, kor, varos)>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT kor (#PCDATA)>
<!ELEMENT varos (#PCDATA)>


<!ATTLIST szemely id ID #REQUIRED>

=== catamaran2/catamaran2-B0WCKKxmlGyak/B0WCKK_1103/szemelyek.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE szemelyek SYSTEM "szemelyek.dtd">

<szemelyek>
	<szemely id="id1">
		<nev>Dora</nev>
		<kor>29</kor>
		<varos>Budapest</varos>
	</szemely>
	<szemely id="id2">
		<nev>Kata</nev>
		<varos>Miskolc</varos>
	</szemely>
	<szemely id="id3">
		<nev>Attila</nev>
		<kor>29</kor>
		<varos>Budapest</varos>
	</szemely>
</szemelyek>
